name: Lint Code Base

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  statuses: write

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@1fa6ba58a88783e9714725cf89ac26d53e80c148 # v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}